### ISSUE TITLE
Bugs/Requests from Discord

### ISSUE THREAD

**Issue by AlwaysAllstar25** [A5H73Y/Carz#21]
Hey, the only two things I can think of that I would love to see added is:
1) An option so the car can climb up all blocks and not look like it's floating. 
2) I know in config there's an option if it requires a key or not, I was thinking an option so you don't even have to start or turn off the engine. Just get in and go, no right clicking the car is needed.

**Comment by A5H73Y** [comment]
Thank you for the feedback.
1. has been addressed by changing the way Climb blocks function, by identifying the block in front of them instead of below.
2. sounds like it could cause confusion and frustration. I think it makes more sense for the user to manually decide to start / stop the engine when wanted.
