### ISSUE TITLE
[DEV] String not found: [StringName]

### ISSUE THREAD

**Issue by TheGreyDiamond** [A5H73Y/Carz#23]
Hi, I forked your repo and tried to compile it. Everything worked well. Except that I'am geting the error: "String not found: [StringName]". Why ist that happening?

**Comment by A5H73Y** [comment]
Looking at your commit history, you've changed the method that get translations by removing the "Message." prefix. You'll see that all the strings in the config.yml start with "Messages." which is why it isn't matching.
This isn't a problem for the main plugin and is something you've introduced so I will be closing this ticket.

**Comment by TheGreyDiamond** [comment]
I just forgot to commit my change back. My newest version looks like this:
```
public static String getTranslation(String translationKey, boolean prefix) {
        if (!Validation.isStringValid(translationKey)) {
            return "Invalid translation.";
        }

        String translated = Carz.getInstance().getSettings().getStringsConfig().getString("Message." + translationKey);
        translated = translated != null ? colour(translated) : "String not found: " + translationKey;
        return prefix ? Carz.getPrefix().concat(translated) : translated;
    }
```
